# Generated by Django 6.0.1 on 2026-02-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='shiny',
            field=models.BooleanField(default=False),
        ),
    ]
