# Generated by Django 6.0.1 on 2026-02-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
