# Generated by Django 6.0.1 on 2026-02-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')], default=0),
        ),
    ]
