# Generated by Django 6.0.1 on 2026-04-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_alter_fishentry_latitude_alter_fishentry_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishentry',
            old_name='Latitude',
            new_name='latitude',
        ),
    ]
