# Generated by Django 6.0.1 on 2026-02-01 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_remove_user_profile_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fish_group', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shiny', models.CharField(max_length=100, null=True)),
                ('fish_avatar', models.ImageField(upload_to='fish_avatar/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='FishDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('entry_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fish_dex_image', models.ImageField(upload_to='fishdex_img/')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angler.fish')),
                ('fish_dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angler.fishdex')),
            ],
            options={
                'unique_together': {('fish', 'fish_dex')},
            },
        ),
        migrations.AddField(
            model_name='fishdex',
            name='fishes',
            field=models.ManyToManyField(blank=True, related_name='fish_dexes', through='angler.FishEntry', to='angler.fish'),
        ),
    ]
