# Generated by Django 6.0.1 on 2026-02-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_alter_fish_shiny'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('lure_type', models.CharField(choices=[('bait', 'Bait'), ('lure', 'Lure')], max_length=100)),
                ('live_bait', models.BooleanField(default=False)),
                ('trailer', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RodAndReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rod_length', models.DecimalField(decimal_places=1, default=6, max_digits=3)),
                ('line', models.CharField(choices=[('monofilament', 'Mono'), ('fluorocarbon', 'Flouro'), ('braid', 'Braid')], max_length=100)),
                ('line_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leader', models.CharField(blank=True, choices=[('monofilament', 'Mono'), ('fluorocarbon', 'Flouro'), ('braid', 'Braid')], max_length=100, null=True)),
                ('leader_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
