# Generated by Django 6.0.4 on 2026-05-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_remove_directmessage_reaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ['created_at']},
        ),
    ]
