# Generated by Django 6.0.1 on 2026-02-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0003_alter_friendrequest_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
