# Generated by Django 6.0.4 on 2026-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0003_alter_groupchat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='gc_img/'),
        ),
    ]
