# Generated by Django 6.0.1 on 2026-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0003_rename_latitude_fishentry_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
