# Generated by Django 6.0.4 on 2026-05-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0004_alter_groupchat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='deleted_at',
        ),
    ]
