# Generated by Django 6.0.1 on 2026-04-16 01:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0005_alter_post_image_alter_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishentry',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[150, 150], upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='fishentry',
            name='fish_dex_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1600, 900], upload_to='fishdex_img/'),
        ),
    ]
