# Generated by Django 6.0.1 on 2026-02-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0005_like_delete_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
