# Generated by Django 6.0.1 on 2026-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0006_rename_author_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishentry',
            name='caught_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
