# Generated by Django 6.0.4 on 2026-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0006_fishentry_thumbnail_alter_fishentry_fish_dex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
