# Generated by Django 6.0.4 on 2026-04-24 20:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0007_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='fish_avatar',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='fish/'),
        ),
    ]
