# Generated by Django 6.0.1 on 2026-03-25 03:31

import angler.models.fish
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0009_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='fish_avatar',
            field=models.ImageField(upload_to=angler.models.fish.content_file_name),
        ),
    ]
