# Generated by Django 6.0.1 on 2026-03-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0010_alter_fish_fish_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishentry',
            name='lure',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='angler.lure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishentry',
            name='tackle',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='angler.rodandreel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishentry',
            name='fish_dex_image',
            field=models.ImageField(blank=True, upload_to='fishdex_img/'),
        ),
    ]
