# Generated by Django 6.0.1 on 2026-03-30 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0011_fishentry_lure_fishentry_tackle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishentry',
            name='lure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='angler.lure'),
        ),
        migrations.AlterField(
            model_name='fishentry',
            name='tackle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='angler.rodandreel'),
        ),
    ]
