# Generated by Django 6.0.1 on 2026-03-31 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0012_alter_fishentry_lure_alter_fishentry_tackle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishentry',
            name='lure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angler.lure'),
        ),
        migrations.AlterField(
            model_name='fishentry',
            name='tackle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angler.rodandreel'),
        ),
    ]
