# Generated by Django 6.0.1 on 2026-03-31 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0013_alter_fishentry_lure_alter_fishentry_tackle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodandreel',
            name='leader_line_pound',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rodandreel',
            name='line_pound',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rodandreel',
            name='reel_type',
            field=models.CharField(choices=[('spinning', 'Spinning'), ('baitcaster', 'Baitcaster'), ('spincast', 'Spincast'), ('fly', 'Fly'), ('conventional', 'Conventional')], default='spinning', max_length=100),
        ),
        migrations.AlterField(
            model_name='rodandreel',
            name='rod_action',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast'), ('extra fast', 'Extra Fast')], default='medium', max_length=100),
        ),
    ]
