# Generated by Django 6.0.1 on 2026-04-02 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0014_rodandreel_leader_line_pound_rodandreel_line_pound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodandreel',
            name='leader_length',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rodandreel',
            name='line_length',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
