# Generated by Django 6.0.4 on 2026-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0014_alter_notification_recipient_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('recipient', models.F('sender')), _negated=True), name='prevent notifications from self'),
        ),
    ]
